version: '2'
services:
  ssl-app:
    image: katka-app-ssl
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
        - 8080:80            
        - 4443:443
    volumes:
        - ./logs/nginx/:/var/log/nginx
        - ./certs:/etc/nginx/certs
